"""Initial migration

Revision ID: 61c8fbe2febd
Revises:
Create Date: 2025-11-29 23:48:54.381253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c8fbe2febd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('workflow_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=False),
    sa.Column('n8n_workflow_id', sa.String(), nullable=False),
    sa.Column('webhook_path', sa.String(), nullable=True),
    sa.Column('workflow_config_json', sa.JSON(), nullable=True),
    sa.Column('workflow_version', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('run_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_configs_id'), 'workflow_configs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_configs_n8n_workflow_id'), 'workflow_configs', ['n8n_workflow_id'], unique=True)
    op.create_index(op.f('ix_workflow_configs_user_id'), 'workflow_configs', ['user_id'], unique=False)
    op.create_table('saved_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_config_id', sa.Integer(), nullable=False),
    sa.Column('preset_name', sa.String(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_config_id'], ['workflow_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_presets_id'), 'saved_presets', ['id'], unique=False)
    op.create_index(op.f('ix_saved_presets_user_id'), 'saved_presets', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_presets_workflow_config_id'), 'saved_presets', ['workflow_config_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_config_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('n8n_execution_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_config_id'], ['workflow_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_id'), 'workflow_executions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_n8n_execution_id'), 'workflow_executions', ['n8n_execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_user_id'), 'workflow_executions', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_config_id'), 'workflow_executions', ['workflow_config_id'], unique=False)
    op.create_table('linkedin_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_execution_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_link', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_results_id'), 'linkedin_results', ['id'], unique=False)
    op.create_index(op.f('ix_linkedin_results_workflow_execution_id'), 'linkedin_results', ['workflow_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_results_workflow_execution_id'), table_name='linkedin_results')
    op.drop_index(op.f('ix_linkedin_results_id'), table_name='linkedin_results')
    op.drop_table('linkedin_results')
    op.drop_index(op.f('ix_workflow_executions_workflow_config_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_user_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_n8n_execution_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_saved_presets_workflow_config_id'), table_name='saved_presets')
    op.drop_index(op.f('ix_saved_presets_user_id'), table_name='saved_presets')
    op.drop_index(op.f('ix_saved_presets_id'), table_name='saved_presets')
    op.drop_table('saved_presets')
    op.drop_index(op.f('ix_workflow_configs_user_id'), table_name='workflow_configs')
    op.drop_index(op.f('ix_workflow_configs_n8n_workflow_id'), table_name='workflow_configs')
    op.drop_index(op.f('ix_workflow_configs_id'), table_name='workflow_configs')
    op.drop_table('workflow_configs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

